name: Deploy application on DEV

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: dev
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Get current Git tag
          id: get_tag
          run: echo "GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo 'v1.0.0')" >> $GITHUB_OUTPUT
  
        - name: Create .env file
          run: |
            echo APP_ENV=dev >> .env
            echo VUE_APP_VERSION=${{ steps.get_tag.outputs.GIT_TAG }} >> .env
            echo VUE_APP_GOOGLE_PLAY_STORE_URL=https://google.com >> .env
            echo VUE_APP_API_PATH_V2=${{ secrets.VUE_APP_API_PATH_V2 }} >> .env

        - name: Install Dependencies
          run: npm install --legacy-peer-deps

        - name: Build package
          run: npm run build-dev
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            
        - name: Deploy to S3
          run: aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }} --delete

        - name: Invalidate CloudFront cache
          if: success()
          run: |
            echo "Invalidating CloudFront distribution..."
            aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
            echo "Invalidation complete."
        
        - name: Deployment Summary
          if: success()
          run: |
            echo "Deployment to DEV environment completed successfully."
