name: E2E Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    
    name: E2E Tests (${{ matrix.browser }})
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get current Git tag
        id: get_tag
        run: echo "GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo 'v1.0.0')" >> $GITHUB_OUTPUT

      - name: Create .env file
        run: |
          echo APP_ENV=test >> .env
          echo VUE_APP_VERSION=${{ steps.get_tag.outputs.GIT_TAG }} >> .env
          echo VUE_APP_GOOGLE_PLAY_STORE_URL=https://google.com >> .env

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Application
        run: npm run build

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          start: npm start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          config: video=false
          spec: cypress/e2e/**/*.cy.js

      - name: Upload Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            cypress/results
            cypress/reports
          if-no-files-found: ignore
          retention-days: 30

  test-summary:
    runs-on: ubuntu-latest
    needs: cypress-tests
    if: always()
    
    steps:
      - name: Test Summary
        run: |
          echo "## E2E Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.cypress-tests.result }}" == "success" ]; then
            echo "✅ All E2E tests passed successfully!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some E2E tests failed. Please check the logs." >> $GITHUB_STEP_SUMMARY
          fi
